# Base URL for immobiliare.it
base_url: "https://www.immobiliare.it"

# Default headers for requests
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
  Accept-Language: "it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"
  Accept-Encoding: "gzip, deflate, br"
  Connection: "keep-alive"
  Referer: "https://www.immobiliare.it/"
  sec-ch-ua: '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"'
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: '"Windows"'
  Sec-Fetch-Dest: "document"
  Sec-Fetch-Mode: "navigate"
  Sec-Fetch-Site: "same-origin"
  Sec-Fetch-User: "?1"
  Upgrade-Insecure-Requests: "1"

# Request settings
request_settings:
  min_delay: 10  # Minimum delay between requests in seconds
  max_delay: 20  # Maximum delay between requests in seconds

# Storage settings
storage_settings:
  type: "file"  # Storage type: "file" or "mongodb"
  settings:
    # File storage settings
    base_path: "data/immobiliare"  # Base path for file storage
    save_json: true  # Enable JSON file dumps 