# Base URL for immobiliare.it
base_url: "https://www.immobiliare.it"

# Default headers for requests
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
  Accept-Language: "en-US,en;q=0.9"
  Accept-Encoding: "gzip, deflate, br"
  Connection: "keep-alive"

# Request settings
request_settings:
  min_delay: 10  # Minimum delay between requests in seconds
  max_delay: 30  # Maximum delay between requests in seconds

# Storage settings
storage_settings:
  type: "file"  # Storage type: "file" or "mongodb"
  settings:
    # File storage settings
    base_path: "data/immobiliare"  # Base path for file storage
    save_json: true  # Enable JSON file dumps 