# Logging configuration for the quant-estate project

# Global logging settings
level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
date_format: '%Y-%m-%d %H:%M:%S'

# Handler configurations
handlers:
  # Console output
  console:
    enabled: true
    level: INFO
    
  # File output
  file:
    enabled: true
    level: DEBUG
    filename: 'quant_estate_{date}.log'
    date_format: '%Y-%m-%d'
    directory: 'logs'
    
  # Module-specific settings
  modules:
    connector:
      level: INFO
      handlers:
        console: true
        file: true
    storage:
      level: DEBUG
      handlers:
        console: true
        file: true
    scraper:
      level: DEBUG
      handlers:
        console: true
        file: true 